os:
    - linux
    - osx

language: java

branches:
  only:
    - master

env:
    - GRAALVM_VERSION="1.0.0-rc11"

#TODO: maybe install other languages for tests
install:
    - |
        if [[ "$GRAALVM_VERSION" != "NONE" ]]; then
          if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="macos"; fi
          if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
          curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$GRAALVM_VERSION-$DOWNLOAD_OS_NAME-amd64.tar.gz" --output graalvm.tar.gz
          tar -xzf graalvm.tar.gz
          export JAVA_HOME="$(pwd)/graalvm-ce-$GRAALVM_VERSION"
          if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
        else
          if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
        fi
    - $JAVA_HOME/bin/gu install ruby
    - $JAVA_HOME/bin/gu install R

git:
  submodules:
    false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

scripts:
  - ./gradlew check
